name: Build and Test

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 8
      uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven

    - name: Setup libraries
      run: |
        chmod +x scripts/setup-libs.sh
        ./scripts/setup-libs.sh

    - name: Build with Maven
      run: mvn -B clean package --file pom.xml

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: face-recognition
        path: target/*.jar
        if-no-files-found: error 