name: Build and Test

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 8
      uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven

    - name: Install Java 3D
      run: |
        mvn dependency:get -Dartifact=org.jogamp.java3d:j3d-core:1.5.2
        mvn dependency:get -Dartifact=org.jogamp.java3d:j3d-utils:1.5.2
        mvn dependency:get -Dartifact=org.jogamp.java3d:vecmath:1.5.2
        sudo mkdir -p /usr/share/java
        sudo cp ~/.m2/repository/org/jogamp/java3d/*/*.jar /usr/share/java/
        echo "export CLASSPATH=/usr/share/java/j3d-core.jar:/usr/share/java/j3d-utils.jar:/usr/share/java/vecmath.jar:$CLASSPATH" >> $GITHUB_ENV

    - name: Create lib directory
      run: mkdir -p lib

    - name: Download JAI libraries
      run: |
        wget https://download.java.net/media/jai/builds/release/1_1_3/jai-1_1_3-lib-linux-amd64.tar.gz
        tar -xzf jai-1_1_3-lib-linux-amd64.tar.gz
        cp jai-1_1_3/lib/*.jar lib/
      continue-on-error: true

    - name: Build with Maven
      run: mvn -B clean package --file pom.xml

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: face-recognition
        path: target/*.jar
        if-no-files-found: error 