name: Build and Test

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 8
      uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven

    - name: Create lib directory
      run: mkdir -p lib

    - name: Download Java 3D libraries
      run: |
        wget https://maven.imagej.net/content/repositories/public/java3d/j3d-core/1.5.2/j3d-core-1.5.2.jar -O lib/j3d-core.jar
        wget https://maven.imagej.net/content/repositories/public/java3d/j3d-utils/1.5.2/j3d-utils-1.5.2.jar -O lib/j3d-utils.jar
        wget https://maven.imagej.net/content/repositories/public/java3d/vecmath/1.5.2/vecmath-1.5.2.jar -O lib/vecmath.jar

    - name: Download JAI libraries
      run: |
        wget https://download.java.net/media/jai/builds/release/1_1_3/jai-1_1_3-lib-linux-amd64.tar.gz
        tar -xzf jai-1_1_3-lib-linux-amd64.tar.gz
        cp jai-1_1_3/lib/*.jar lib/
      continue-on-error: true

    - name: Build with Maven
      run: mvn -B clean package --file pom.xml

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: face-recognition
        path: target/*.jar
        if-no-files-found: error 