name: Build and Test

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 8
      uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven

    - name: Create lib directory
      run: mkdir -p lib

    - name: Download Java 3D libraries
      run: |
        wget https://download.java.net/media/java3d/builds/release/1.5.2/java3d-1.5.2-linux-amd64.zip -O java3d.zip
        unzip -j java3d.zip "*/lib/*.jar" -d lib/
        rm java3d.zip
      continue-on-error: true

    - name: Download JAI libraries
      run: |
        wget https://download.java.net/media/jai/builds/release/1_1_3/jai-1_1_3-lib-linux-amd64.tar.gz
        tar -xzf jai-1_1_3-lib-linux-amd64.tar.gz
        cp jai-1_1_3/lib/*.jar lib/
      continue-on-error: true

    - name: Build with Maven
      run: mvn -B clean package --file pom.xml

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: face-recognition
        path: target/*.jar
        if-no-files-found: error 